-- liquibase formatted sql

-- changeset henry:20221116_insert_user_book_rate_dummy_data

INSERT INTO user_book_rate (user_id, book_id, rate, comment,created_date, modified_date, created_by, modified_by) VALUES
(1, 1, 5, 'Amazing start to the series! Loved every page.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(1, 2, 5, 'Just as good as the first!',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(1, 3, 4, 'Great fantasy but heavy reading.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(1, 5, 5, 'Mind-bending science fiction masterpiece.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(1, 11, 4, 'Interesting mystery, kept me engaged.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(2, 1, 5, 'Magical world-building is incredible.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(2, 4, 4, 'Classic mystery, very well constructed.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(2, 7, 5, 'Life-changing philosophical novel.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(2, 9, 4, 'Fascinating insights about success.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(2, 15, 5, 'Changed how I think about decision-making.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(3, 3, 5, 'Epic fantasy with complex characters.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(3, 6, 5, 'Terrifying and unforgettable.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(3, 8, 4, 'Beautiful storytelling about history.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(3, 12, 4, 'Excellent sci-fi collection.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(4, 1, 5, 'Perfect for young adults and adults alike.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(4, 10, 5, 'Addictive paranormal romance.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(4, 14, 4, 'Strong female protagonist, great adventure.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(4, 7, 5, 'Truly inspirational and motivating.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(5, 2, 5, 'Continued brilliance throughout.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(5, 5, 5, 'Foundation of science fiction greatness.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(5, 11, 4, 'Page-turner mystery thriller.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(5, 13, 4, 'Classic Agatha Christie at her best.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(6, 4, 5, 'Masterpiece of detective fiction.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(6, 7, 5, 'Everyone should read this book.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(6, 9, 3, 'Interesting but some parts were slow.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(7, 3, 5, 'Complex world-building, worth the read.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(7, 8, 5, 'Powerful exploration of war and humanity.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(7, 15, 4, 'Insightful look at human behavior.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(8, 1, 4, 'Great introduction to the wizarding world.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(8, 6, 4, 'Creepy and compelling.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(8, 10, 5, 'Urban fantasy at its finest.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(8, 12, 4, 'Thoughtful robot stories.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(9, 5, 5, 'Visionary science fiction work.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(9, 11, 5, 'Clever plot with great twist.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(9, 14, 5, 'Exceptional character development.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(10, 7, 5, 'Life-altering perspective on destiny.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(10, 9, 4, 'Great insights into achievement.',NOW(), NOW(), 'SYSTEM', 'SYSTEM'),
(10, 15, 5, 'Essential reading on thinking.',NOW(), NOW(), 'SYSTEM', 'SYSTEM');

